[2025-01-05T15:52:58.077+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T15:52:58.093+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_check manual__2025-01-05T15:52:57.094605+00:00 [queued]>
[2025-01-05T15:52:58.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_check manual__2025-01-05T15:52:57.094605+00:00 [queued]>
[2025-01-05T15:52:58.096+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T15:52:58.102+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): file_check> on 2025-01-05 15:52:57.094605+00:00
[2025-01-05T15:52:58.109+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3368) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T15:52:58.109+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'file_check', 'manual__2025-01-05T15:52:57.094605+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmpngc6mpom']
[2025-01-05T15:52:58.110+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask file_check
[2025-01-05T15:52:58.110+0000] {standard_task_runner.py:63} INFO - Started process 3370 to run task
[2025-01-05T15:52:58.131+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.file_check manual__2025-01-05T15:52:57.094605+00:00 [running]> on host 0509704c18d8
[2025-01-05T15:52:58.171+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='file_check' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T15:52:57.094605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T15:52:57.094605+00:00'
[2025-01-05T15:52:58.172+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T15:52:58.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T15:52:58.179+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_banking_tinkoff.py", line 15, in file_check
    raise FileNotFoundError(f'Папка {path} не существует')
FileNotFoundError: Папка /opt/finflow/data/banking/alfa/new не существует
[2025-01-05T15:52:58.185+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_banking_tinkoff, task_id=file_check, run_id=manual__2025-01-05T15:52:57.094605+00:00, execution_date=20250105T155257, start_date=20250105T155258, end_date=20250105T155258
[2025-01-05T15:52:58.310+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task file_check (Папка /opt/finflow/data/banking/alfa/new не существует; 3370)
[2025-01-05T15:52:58.345+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-05T15:52:58.355+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T15:52:58.356+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
