[2025-01-05T21:13:55.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T21:13:55.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:13:51.754422+00:00 [queued]>
[2025-01-05T21:13:55.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:13:51.754422+00:00 [queued]>
[2025-01-05T21:13:55.203+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T21:13:55.207+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_db> on 2025-01-05 21:13:51.754422+00:00
[2025-01-05T21:13:55.211+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'load_db', 'manual__2025-01-05T21:13:51.754422+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmp1onbvnqx']
[2025-01-05T21:13:55.212+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask load_db
[2025-01-05T21:13:55.212+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T21:13:55.213+0000] {standard_task_runner.py:63} INFO - Started process 314 to run task
[2025-01-05T21:13:55.231+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:13:51.754422+00:00 [running]> on host 3f8f12119728
[2025-01-05T21:13:55.265+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='load_db' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T21:13:51.754422+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T21:13:51.754422+00:00'
[2025-01-05T21:13:55.266+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T21:13:55.354+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T21:13:55.355+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_banking_tinkoff.py", line 63, in load_db
    print(POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB)
          ^^^^^^^^^^^^^
NameError: name 'POSTGRES_USER' is not defined
[2025-01-05T21:13:55.361+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_banking_tinkoff, task_id=load_db, run_id=manual__2025-01-05T21:13:51.754422+00:00, execution_date=20250105T211351, start_date=20250105T211355, end_date=20250105T211355
[2025-01-05T21:13:55.365+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 60 for task load_db (name 'POSTGRES_USER' is not defined; 314)
[2025-01-05T21:13:55.397+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-05T21:13:55.405+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T21:13:55.406+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
