[2025-01-05T21:34:56.664+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T21:34:56.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:34:53.669110+00:00 [queued]>
[2025-01-05T21:34:56.679+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:34:53.669110+00:00 [queued]>
[2025-01-05T21:34:56.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T21:34:56.684+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_db> on 2025-01-05 21:34:53.669110+00:00
[2025-01-05T21:34:56.688+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'load_db', 'manual__2025-01-05T21:34:53.669110+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmpnas9tm_j']
[2025-01-05T21:34:56.689+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask load_db
[2025-01-05T21:34:56.689+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=515) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T21:34:56.690+0000] {standard_task_runner.py:63} INFO - Started process 517 to run task
[2025-01-05T21:34:56.708+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.load_db manual__2025-01-05T21:34:53.669110+00:00 [running]> on host 6d9883a799ac
[2025-01-05T21:34:56.740+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='load_db' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T21:34:53.669110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T21:34:53.669110+00:00'
[2025-01-05T21:34:56.740+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T21:34:56.842+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T21:34:56.842+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "13.12.2024"
LINE 1: ...на Т.', 0.0, 0.0, 1250.0),('2024-12-13 00:54:33', '13.12.202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_banking_tinkoff.py", line 67, in load_db
    load_df.to_sql(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.DataError: (psycopg2.errors.DatetimeFieldOverflow) date/time field value out of range: "13.12.2024"
LINE 1: ...на Т.', 0.0, 0.0, 1250.0),('2024-12-13 00:54:33', '13.12.202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

[SQL: INSERT INTO banking_tinkoff (operation_date, payment_date, card_number, status, amount, currency, amount_payment, currency_payment, cashback, category, mcc, description, bonus, invest_round, amount_round) VALUES (%(operation_date)s, %(payment_date)s, %(card_number)s, %(status)s, %(amount)s, %(currency)s, %(amount_payment)s, %(currency_payment)s, %(cashback)s, %(category)s, %(mcc)s, %(description)s, %(bonus)s, %(invest_round)s, %(amount_round)s)]
[parameters: ({'operation_date': '2024-12-01 11:44:26', 'payment_date': '01.12.2024', 'card_number': None, 'status': 'OK', 'amount': -1300.0, 'currency': 'RUB', 'amount_payment': -1300.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Алина В.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 1300.0}, {'operation_date': '2024-12-01 11:44:41', 'payment_date': '01.12.2024', 'card_number': None, 'status': 'OK', 'amount': -270.0, 'currency': 'RUB', 'amount_payment': -270.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Екатерина Т.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 270.0}, {'operation_date': '2024-12-01 12:03:44', 'payment_date': '01.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': -1314.92, 'currency': 'RUB', 'amount_payment': -1314.92, 'currency_payment': 'RUB', 'cashback': 13.0, 'category': 'Супермаркеты', 'mcc': 5411.0, 'description': 'Перекрёсток', 'bonus': 13.0, 'invest_round': 85.08, 'amount_round': 1400.0}, {'operation_date': '2024-12-01 12:09:00', 'payment_date': '01.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': -570.0, 'currency': 'RUB', 'amount_payment': -570.0, 'currency_payment': 'RUB', 'cashback': 5.0, 'category': 'Супермаркеты', 'mcc': 5411.0, 'description': 'ВкусВилл', 'bonus': 5.0, 'invest_round': 30.0, 'amount_round': 600.0}, {'operation_date': '2024-12-01 19:43:31', 'payment_date': '01.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': 12400.0, 'currency': 'RUB', 'amount_payment': 12400.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Алина В.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 12400.0}, {'operation_date': '2024-12-01 21:59:46', 'payment_date': '01.12.2024', 'card_number': None, 'status': 'OK', 'amount': -7000.0, 'currency': 'RUB', 'amount_payment': -7000.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Зайниддин Ш.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 7000.0}, {'operation_date': '2024-12-02 17:58:28', 'payment_date': '02.12.2024', 'card_number': '*7277', 'status': 'OK', 'amount': -409.0, 'currency': 'RUB', 'amount_payment': -409.0, 'currency_payment': 'RUB', 'cashback': 4.0, 'category': 'Сервис', 'mcc': 4215.0, 'description': 'Яндекс Доставка', 'bonus': 4.0, 'invest_round': 91.0, 'amount_round': 500.0}, {'operation_date': '2024-12-03 18:04:00', 'payment_date': '03.12.2024', 'card_number': '*7277', 'status': 'OK', 'amount': 3816.2, 'currency': 'RUB', 'amount_payment': 3816.2, 'currency_payment': 'RUB', 'cashback': -38.0, 'category': 'Ж/д билеты', 'mcc': 4112.0, 'description': 'РЖД', 'bonus': -38.0, 'invest_round': 0.0, 'amount_round': 3816.2}  ... displaying 10 of 109 total bound parameter sets ...  {'operation_date': '2024-12-31 17:38:42', 'payment_date': '31.12.2024', 'card_number': '*7277', 'status': 'OK', 'amount': 5307.0, 'currency': 'RUB', 'amount_payment': 5307.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': 6536.0, 'description': 'Пополнение. avito.ru MOSKVA RUS', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 5307.0}, {'operation_date': '2024-12-31 17:39:21', 'payment_date': '31.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': 5326.0, 'currency': 'RUB', 'amount_payment': 5326.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Перевод средств от организации', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 5326.0})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2025-01-05T21:34:56.850+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_banking_tinkoff, task_id=load_db, run_id=manual__2025-01-05T21:34:53.669110+00:00, execution_date=20250105T213453, start_date=20250105T213456, end_date=20250105T213456
[2025-01-05T21:34:56.855+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task load_db ((psycopg2.errors.DatetimeFieldOverflow) date/time field value out of range: "13.12.2024"
LINE 1: ...на Т.', 0.0, 0.0, 1250.0),('2024-12-13 00:54:33', '13.12.202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

[SQL: INSERT INTO banking_tinkoff (operation_date, payment_date, card_number, status, amount, currency, amount_payment, currency_payment, cashback, category, mcc, description, bonus, invest_round, amount_round) VALUES (%(operation_date)s, %(payment_date)s, %(card_number)s, %(status)s, %(amount)s, %(currency)s, %(amount_payment)s, %(currency_payment)s, %(cashback)s, %(category)s, %(mcc)s, %(description)s, %(bonus)s, %(invest_round)s, %(amount_round)s)]
[parameters: ({'operation_date': '2024-12-01 11:44:26', 'payment_date': '01.12.2024', 'card_number': None, 'status': 'OK', 'amount': -1300.0, 'currency': 'RUB', 'amount_payment': -1300.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Алина В.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 1300.0}, {'operation_date': '2024-12-01 11:44:41', 'payment_date': '01.12.2024', 'card_number': None, 'status': 'OK', 'amount': -270.0, 'currency': 'RUB', 'amount_payment': -270.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Екатерина Т.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 270.0}, {'operation_date': '2024-12-01 12:03:44', 'payment_date': '01.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': -1314.92, 'currency': 'RUB', 'amount_payment': -1314.92, 'currency_payment': 'RUB', 'cashback': 13.0, 'category': 'Супермаркеты', 'mcc': 5411.0, 'description': 'Перекрёсток', 'bonus': 13.0, 'invest_round': 85.08, 'amount_round': 1400.0}, {'operation_date': '2024-12-01 12:09:00', 'payment_date': '01.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': -570.0, 'currency': 'RUB', 'amount_payment': -570.0, 'currency_payment': 'RUB', 'cashback': 5.0, 'category': 'Супермаркеты', 'mcc': 5411.0, 'description': 'ВкусВилл', 'bonus': 5.0, 'invest_round': 30.0, 'amount_round': 600.0}, {'operation_date': '2024-12-01 19:43:31', 'payment_date': '01.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': 12400.0, 'currency': 'RUB', 'amount_payment': 12400.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Алина В.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 12400.0}, {'operation_date': '2024-12-01 21:59:46', 'payment_date': '01.12.2024', 'card_number': None, 'status': 'OK', 'amount': -7000.0, 'currency': 'RUB', 'amount_payment': -7000.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Зайниддин Ш.', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 7000.0}, {'operation_date': '2024-12-02 17:58:28', 'payment_date': '02.12.2024', 'card_number': '*7277', 'status': 'OK', 'amount': -409.0, 'currency': 'RUB', 'amount_payment': -409.0, 'currency_payment': 'RUB', 'cashback': 4.0, 'category': 'Сервис', 'mcc': 4215.0, 'description': 'Яндекс Доставка', 'bonus': 4.0, 'invest_round': 91.0, 'amount_round': 500.0}, {'operation_date': '2024-12-03 18:04:00', 'payment_date': '03.12.2024', 'card_number': '*7277', 'status': 'OK', 'amount': 3816.2, 'currency': 'RUB', 'amount_payment': 3816.2, 'currency_payment': 'RUB', 'cashback': -38.0, 'category': 'Ж/д билеты', 'mcc': 4112.0, 'description': 'РЖД', 'bonus': -38.0, 'invest_round': 0.0, 'amount_round': 3816.2}  ... displaying 10 of 109 total bound parameter sets ...  {'operation_date': '2024-12-31 17:38:42', 'payment_date': '31.12.2024', 'card_number': '*7277', 'status': 'OK', 'amount': 5307.0, 'currency': 'RUB', 'amount_payment': 5307.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': 6536.0, 'description': 'Пополнение. avito.ru MOSKVA RUS', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 5307.0}, {'operation_date': '2024-12-31 17:39:21', 'payment_date': '31.12.2024', 'card_number': '*9688', 'status': 'OK', 'amount': 5326.0, 'currency': 'RUB', 'amount_payment': 5326.0, 'currency_payment': 'RUB', 'cashback': None, 'category': 'Переводы', 'mcc': None, 'description': 'Перевод средств от организации', 'bonus': 0.0, 'invest_round': 0.0, 'amount_round': 5326.0})]
(Background on this error at: https://sqlalche.me/e/14/9h9h); 517)
[2025-01-05T21:34:56.883+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-05T21:34:56.892+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T21:34:56.893+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
