[2025-01-05T20:42:43.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-05T20:42:43.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T20:42:41.591749+00:00 [queued]>
[2025-01-05T20:42:43.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T20:42:41.591749+00:00 [queued]>
[2025-01-05T20:42:43.615+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-05T20:42:43.621+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): file_processing> on 2025-01-05 20:42:41.591749+00:00
[2025-01-05T20:42:43.626+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=597) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T20:42:43.625+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_banking_tinkoff', 'file_processing', 'manual__2025-01-05T20:42:41.591749+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/raw_banking_tinkoff.py', '--cfg-path', '/tmp/tmpk6ga5atc']
[2025-01-05T20:42:43.626+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask file_processing
[2025-01-05T20:42:43.626+0000] {standard_task_runner.py:63} INFO - Started process 599 to run task
[2025-01-05T20:42:43.645+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_banking_tinkoff.file_processing manual__2025-01-05T20:42:41.591749+00:00 [running]> on host 928815d407f9
[2025-01-05T20:42:43.677+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='raw_banking_tinkoff' AIRFLOW_CTX_TASK_ID='file_processing' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T20:42:41.591749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T20:42:41.591749+00:00'
[2025-01-05T20:42:43.678+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-05T20:42:43.765+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-05T20:42:43.765+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'xlrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/raw_banking_tinkoff.py", line 40, in file_processing
    df_file = pd.read_excel(file_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_xlrd.py", line 44, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.
[2025-01-05T20:42:43.770+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=raw_banking_tinkoff, task_id=file_processing, run_id=manual__2025-01-05T20:42:41.591749+00:00, execution_date=20250105T204241, start_date=20250105T204243, end_date=20250105T204243
[2025-01-05T20:42:43.774+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task file_processing (Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.; 599)
[2025-01-05T20:42:43.815+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-05T20:42:43.823+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T20:42:43.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
